name: release artifacts
on:
  push:
    tags:
      - v*
  workflow_dispatch:

concurrency:
  group: release_workflow
  cancel-in-progress: true

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build apk
      - uses: actions/upload-artifact@v3
        with:
          name: frigoligo-${{ github.ref_name }}.apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build linux
      - run: tar czf frigoligo-${{ github.ref_name }}-linux-x64.tar.gz build/linux/x64/release/bundle/
      - uses: actions/upload-artifact@v3
        with:
          name: frigoligo-${{ github.ref_name }}-linux-x64.tar.gz
          path: frigoligo-${{ github.ref_name }}-linux-x64.tar.gz

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build windows
      - run: Compress-Archive -Path build\windows\runner\Release\* -DestinationPath frigoligo-${{ github.ref_name }}-windows-x64.zip
      - uses: actions/upload-artifact@v3
        with:
          name: frigoligo-${{ github.ref_name }}-windows-x64.zip
          path: frigoligo-${{ github.ref_name }}-windows-x64.zip
